### ISSUE TITLE
[Skylab] In app notification shows User id instead of User's name

### ISSUE THREAD

**Issue by Sander-Kornev** [AppLozic/Applozic-Chat-iOS-Framework#94]
Hi

1. We have the following issue, in iOS application (Applozic SDK v.6.9.0) when user gets a message from another user for the first time, in app notification author shows User ID instead of User Name (message1.png).

After the second message we can show user name in both places: author and message (message2.png).

And after we go the Applozic native one to one chat screen with that user and get back to another screen, this time in app notification is correct (message3.png).

Also I attached logs from console (in follow up email).

Please take a look and provide an estimation when it can be fixed.

2. And one more question, because of the following code in ALLogs.h

#define APPLOZIC_ENABLE_FLAG 1

#ifdef APPLOZIC_ENABLE_FLAG
#define NSLog(args...) ALExtendNSLog(__FILE__,__LINE__,__PRETTY_FUNCTION__,args);
#else
#define NSLog(x...)
#endif

NSLogs from my app get redefined in your cocoapod framework each time I reinstall pods. Obviously I can't set your flag APPLOZIC_ENABLE_FLAG to 0 or comment this code because I will modify external dependency and it would work only until next update of my pods in the project.

Please suggest how we can get rid of your redefinition more consistent.

![1message](https://user-images.githubusercontent.com/3295273/57968154-9040b000-796f-11e9-900e-b94f8906592d.PNG)
![2message](https://user-images.githubusercontent.com/3295273/57968155-9040b000-796f-11e9-84b5-0402b17f16a2.PNG)
![3message](https://user-images.githubusercontent.com/3295273/57968156-90d94680-796f-11e9-94b9-c5bd0290adf6.PNG)

**Comment by Sunilkumarr** [comment]
@Sander-Kornev We have fixed the issue in  latest version use ``` pod 'Applozic', '~> 6.10.0' ```

**Comment by Sander-Kornev** [comment]
Hi @Sunilkumarr . Thanks.
However, I still see an issue with different formats of messages like this
<img width="650" alt="Screenshot at May 30 21-29-43" src="https://user-images.githubusercontent.com/3295273/58655130-1d95e400-8322-11e9-89f8-3caaf0f5935c.png">
Will you be able to fix this as well?

**Comment by Sunilkumarr** [comment]
@Sander-Kornev I'm trying to replicate this issue and will update you on Monday with timelines.
